steps:
  - label: Build docker environment...
    command: make dockerenvbuild
  
  - wait

  - label: Building something...
    command: .buildkite/build_something.sh && docker container prune -f

  - wait

  - label: Uploading artifacts...
    command: .buildkite/setup_and_upload_artifacts.sh
